FROM registry.access.redhat.com/ubi8/ubi as build

RUN dnf update -qy && \
    dnf install --setopt=install_weak_deps=False -qy \
    go \
    make \
    && \
    dnf clean all -y &&\
    rm -rf /var/cache/yum

WORKDIR /src
COPY gobot/go.mod .
COPY gobot/go.sum .
RUN go mod download
COPY gobot/ .
RUN NOISY_BUILD=y \
    make gobot

FROM registry.access.redhat.com/ubi8/ubi as gobot

COPY --from=build /src/gobot /instructlab-bot
ENTRYPOINT [ "/instructlab-bot" ]
