---
- name: Install git
  ansible.builtin.dnf:
    name: git
    state: present
  become: true

- name: Clone the repository # noqa latest[git]
  ansible.builtin.git:
    repo: 'https://{{ github_token }}@github.com/redhat-et/instruct-lab-bot'
    dest: "~/instruct-lab-bot"

- name: Run the install script in the background and log output # noqa no-changed-when
  ansible.builtin.shell: |
    cd ~/instruct-lab-bot/scripts
    nohup ./install-worker.sh install --gpu-type cuda \
    --github-token "{{ github_token }}" \
    --aws-access-key-id "{{ aws_access_key_id }}" \
    --aws-secret-access-key "{{ aws_secret_access_key }}" > install-worker.log 2>&1 &

- name: Pause for 35 minutes to allow the script to complete
  ansible.builtin.pause:
    minutes: 35

- name: Print the output of the install script log # noqa no-changed-when
  ansible.builtin.command: cat /home/{{ ansible_user }}/instruct-lab-bot/scripts/install-worker.log
  register: log_content

- name: Display log content
  ansible.builtin.debug:
    msg: "{{ log_content.stdout }}"

- name: Reboot the system
  ansible.builtin.reboot:
  become: true

- name: Wait for the system to come back
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 500

- name: Run the install script again after reboot # noqa no-changed-when
  ansible.builtin.shell: |
    cd ~/instruct-lab-bot/scripts
    ./install-worker.sh install \
    --gpu-type cuda \
    --github-token "{{ github_token }}" \
    --aws-access-key-id "{{ aws_access_key_id }}" \
    --aws-secret-access-key "{{ aws_secret_access_key }}"

- name: Pause for 10 minutes to allow the script to complete
  ansible.builtin.pause:
    minutes: 10
