### Globals ###
aws_region: us-east-1                 # AWS region
aws_image_id: ami-0746fc234df9c1ee0   # Fedora39
aws_key_name: instruct-bot            # the key pair on your aws account to use
aws_instance_type: g4dn.xlarge        # low tier GPU $.50 per/hr
aws_nodetype_tag: instruct-bot-qa     # Unique tag identifier for ec2 instances
ansible_user: fedora                  # this is the default user ID for your AMI image. Example, AWS AMI is ec2-user etc
security_group_description: "Instruct Bot SG"
inventory_location: inventory.txt     # leaving this as is will use the inventory.txt file in the base directory

### VPC Details ###
secgroup_name: instruct-bot-sg        # the security group name can be an existing group or else it will be created by the playbook
node_count: 1                         # the number of nodes to be deployed
vpc_id: vpc-27b7165a                  # VPC id
aws_subnet: subnet-c8db48e9           # VPC subnet id
