apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: ILWORKER_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: instructlab-bot
                  key: ILWORKER_GITHUB_TOKEN
          args:
            - /instructlab-bot-worker
            - --test
            - --redis
            - redis:6379
            - generate
          image: {{ .Values.image }} # ghcr.io/instructlab/instructlab-bot/instructlab-serve:main
          name: worker
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
