---
- name: Remove Packages
  ansible.builtin.dnf:
    name:
      - nvidia-docker
      - nvidia-docker2
      - nvidia-container-runtime
    state: absent
    autoremove: true

- name: Add NVIDIA drivers
  ansible.builtin.get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/fedora39/x86_64/cuda-fedora39.repo
    dest: "/etc/yum.repos.d/cuda-fedora39.repo"
    mode: "0644"
    owner: root
    group: root

- name: Install NVIDIA kmod
  ansible.builtin.dnf:
    name: "@nvidia-driver:latest-dkms"
    state: present
    update_cache: true
  register: nvidia_install_kmod

- name: Install CUDA Toolkit
  ansible.builtin.dnf:
    name: "cuda-toolkit"
    state: present
    update_cache: true
  register: nvidia_install_cuda

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 500
    msg: "Rebooting to load NVIDIA drivers"
  when: nvidia_install_kmod.changed or nvidia_install_cuda.changed

- name: Add Repo
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
    dest: "/etc/yum.repos.d/nvidia-container-toolkit.repo"
    mode: "0644"
    owner: root
    group: root

- name: Install Packages
  ansible.builtin.dnf:
    name:
      - nvidia-container-runtime
    state: present
    update_cache: true
  notify: Restart Docker

- name: Set docker daemon configuration
  ansible.builtin.shell: |
    nvidia-ctk runtime configure --runtime=docker
  changed_when: true
  notify: Restart Docker
