---
- name: Log into GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: instructlab-bot
    password: "{{ github_token }}"
    reauthorize: true

- name: Set git credential helper
  community.general.git_config:
    name: credential.helper
    value: store
    scope: global

- name: Set credentials
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.git-credentials"
    content: |
      https://instructlab-bot:{{ github_token }}@github.com
    mode: "0600"

- name: Check if the taxonomy directory exists
  ansible.builtin.stat:
    path: "{{ taxonomy_directory }}"
  register: taxonomy_dir

- name: Clone the taxonomy repository
  ansible.builtin.git:  # noqa latest[git]
    repo: https://github.com/instructlab/taxonomy
    dest: "{{ taxonomy_directory }}"
    clone: true
    update: true

- name: Install additional packages
  ansible.builtin.pip:
    name: huggingface-hub
    state: present

- name: Create the models directory
  ansible.builtin.file:
    path: "{{ models_directory }}"
    state: directory
    mode: "0755"

- name: Check if model exists
  ansible.builtin.stat:
    path: "{{ models_directory }}/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  register: model

- name: Download model from Hugging Face  # noqa no-changed-when
  when: not model.stat.exists
  ansible.builtin.shell: |
    huggingface-cli download \
      TheBloke/Mistral-7B-Instruct-v0.1-GGUF \
      mistral-7b-instruct-v0.1.Q4_K_M.gguf \
      --local-dir {{ models_directory }} \
      --local-dir-use-symlinks False
  args:
    executable: /bin/bash
    chdir: "{{ models_directory }}"

- name: Initialize lab  # noqa no-changed-when
  ansible.builtin.copy:
    dest: "{{ app_directory }}/config.yaml"
    mode: preserve
    content: |
      chat:
        context: default
        greedy_mode: false
        logs_dir: data/chatlogs
        model: mistral-7b-instruct-v0.1
        session: null
        vi_mode: false
        visible_overflow: true
      general:
        log_level: INFO
      generate:
        model: mistral-7b-instruct-v0.1
        num_cpus: 10
        num_instructions: 100
        output_dir: generated
        prompt_file: prompt.txt
        seed_file: seed_tasks.json
        taxonomy_base: origin/main
        taxonomy_path: taxonomy
      serve:
        gpu_layers: -1
        host_port: localhost:8000
        max_ctx_size: 4096
        model_path: models/mistral-7b-instruct-v0.1.Q4_K_M.gguf

- name: Serve the model
  community.docker.docker_container:
    name: instructlab-serve
    image: ghcr.io/instructlab/instructlab-bot/instructlab-serve:main
    pull: always
    state: started
    ports:
      - "8000:8000"
    volumes:
      - "/home/{{ ansible_user }}/instructlab:/data"
