apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: ILWORKER_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: instruct-lab-bot
                  key: ILWORKER_GITHUB_TOKEN
          args:
            - /bin/instruct-lab-bot
            - worker
            - --test
            - --redis
            - redis:6379
          image: ghcr.io/instruct-lab/instruct-lab-bot/instruct-lab-serve:main
          name: worker
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
