# Default values for instructlab-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

bot:
  enabled: true

worker:
  enabled: true

redis:
  enabled: true
  
